[[pages]]
path = "homepage.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "pages/single.py"
name = "Single Data Entry"
icon = "ğŸ“ƒ"

[[pages]]
path = "pages/multi.py"
name = "Multiple Data Entry"
icon = "ğŸ“‚"
